[project]
name = "quiz-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai-agents>=0.4.1",
    "streamlit>=1.50.0",
]
